version: 3.9
services:
  # PostgreSQL
  db:
    image: postgres:16
    container_name: sisnot-postgres-db
    environment:
      POSTGRES_DB: Sisnot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432" 
    volumes:
      - ./postgres-data:/var/lib/postgresql/data 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d Sisnot"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # back
  app:
    build: ./Sisnot 
    container_name: sisnot-app
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/Sisnot 
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  # API Gateway
  api-gateway:
    build: ./API-GATEWAY 
    container_name: sisnot-api-gateway
    ports:
      - "8080:8080"
    environment:

      SISNOT_SERVICE_URI: http://app:8081

    depends_on:
      app:
        condition: service_started 
    restart: unless-stopped