version: '3.8'

services: 
 # PostgreSQL
  postgres:
    image: postgres:16
    container_name: sisnot-postgres-db
    environment:
      POSTGRES_DB: Sisnot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - ./Sisnot-back2/postgres-data:/var/lib/postgresql/data

 # BACKEND
  backend:
    build: ./Sisnot-back2/Sisnot 
    container_name: sisnot-backend
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://backend:5432/Sisnot 
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
    depends_on:
    - postgres

 # API _ GATEWAY 
  api-gateway: 
    build: ./Sisnot-back2/API-GATEWAY
    container_name: sisnot-api-gateway
    ports:
      - "8080:8080"
    environment:
      SISNOT_SERVICE_URI: http://backend:8081
    depends_on:
     - backend
    
# FRONTEND
  frontend: 
    build: ./SisnotFront 
    container_name: sisnot-frontend
    ports:
     - "4200:4200"
    environment:
      REACT_APP_API_URL: http://api-gateway:8080 
    depends_on:
    - api-gateway